# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np
arr = np.random.rand(4,7)*20
#arr2max ==1, arr2min ==0
#max(arr)->1, arr1 = arr/max(arr), max(arr1) ==1,
#min(arr1) = min(arr)/max(arr) 
#------
#min(arr)->0, arr1 = arr - min(arr), min(arr1)==0,
#max(arr1) = max(arr) - min(arr)
#arr2 = arr1/max(arr)
arr_new = arr/(arr.max() - arr.min())+arr.min()/(arr.min() - arr.max())
print(arr)
print(arr_new)

[[ 1.73953224 12.60796742  4.26973844 19.99775989  9.21797544  4.63311818
   4.62541039]
 [11.26779031  9.86464113 14.27700544 10.72115981 15.79282106 13.26072386
  15.68232966]
 [ 2.59030296 18.75670912  9.41141369  4.27986478  2.5092257   0.24375227
   6.3382847 ]
 [12.7147899   2.72830466 18.51793304  0.13776126 18.66439202 19.91613343
   7.18118725]]
[[0.08065313 0.62790569 0.20805526 1.         0.45721122 0.22635233
  0.22596422]
 [0.56042446 0.48977243 0.71194588 0.53290027 0.78827094 0.66077359
  0.78270743]
 [0.12349153 0.93751003 0.46695131 0.20856515 0.11940909 0.00533691
  0.31221168]
 [0.63328447 0.13044026 0.92548706 0.         0.93286163 0.99588991
  0.3546539 ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
arr = np.random.randint(0,11,(8, 10))
print(arr)
print(f'Элементы строки: {arr[np.argmin(np.sum(arr, axis=1))]}, Индекс: {np.argmin(np.sum(arr, axis=1))}')

[[ 2  4  5  8 10 10  7 10  0  7]
 [ 5  5  6  5  2  1  0  9  3  5]
 [ 8 10  4  0  9  3  1  1  3  7]
 [ 0  9  0  5  6  3  0  7  8 10]
 [ 3  7  9  5  8  5  7  4  2  6]
 [ 7  0  7  2  5  8  3  0  4  8]
 [ 8  9  6  8 10  5  0 10  1  9]
 [ 4  3  7  7  4  5  7  1 10  9]]
Элементы строки: [5 5 6 5 2 1 0 9 3 5], Индекс: 1


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
a = np.array([10, 20])
b = np.array([3, -5])
res_1 = np.sqrt(((b - a)**2).sum())
res_2 = np.linalg.norm(b-a)
print(res_1 == res_2)

True


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)

print(X)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
file = np.loadtxt('minutes_n_ingredients.csv', skiprows=1, delimiter=',', max_rows=5, dtype='int32')
print(file)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
file = np.loadtxt('minutes_n_ingredients.csv', skiprows=1, delimiter=',', dtype='int32')
mean_2 = np.mean(file[:,(1, 2)], axis=0)
print(mean_2)
max = np.max(file[:,(1, 2)], axis=0)
print(max)
min = np.min(file[:,(1, 2)], axis=0)
print(min)
median = np.median(file[:,(1, 2)], axis=0)
print(median)


[2.16010017e+04 9.05528000e+00]
[2147483647         39]
[0 1]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
val = np.quantile(file[:, 1:2], 0.75)
print(val)
file = file[file[:,1]<=val]
file.shape

65.0


(75461, 3)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
mask = (file == 0)
print(len(file[mask]))
np.place(file[:,1], file[:, 1]==0, 1)

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
un = np.unique(file[:, (1, 2)], axis=0)
un.size

2250

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(np.unique(file[:, 2]))
len(np.unique(file[:, 2]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 33 34]


32

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
mask = file[:, 2] <=5
file_2 = file[mask]
file_2.shape

(14890, 3)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
(file[:, 2]/file[:, 1]).max()

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
file[file[:, 1].argsort()[::-1]][:100, 2].mean()

10.06

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
file[np.random.randint(file.shape[0], size=10),:]

array([[ 61251,     20,     12],
       [384233,     60,     18],
       [468146,     60,      7],
       [ 56398,     25,      9],
       [232454,     35,      4],
       [158043,     50,      9],
       [496609,     15,      3],
       [395909,     20,     10],
       [148961,     60,     13],
       [ 60832,     40,      9]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
mask = file[:, 2] < np.mean(file[:, 2])
print(100*len(file[mask])/len(file))

52.51056837306688


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
mask_1 = (file[:, 1] <= 20) & (file[:, 2] <= 5)

new_file = np.c_[file, mask_1]
new_file

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [ 43407,     35,      7,      0],
       [498432,     65,     15,      0],
       [370915,      5,      4,      1]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [ ]:
mask = (new_file[:, 3] == 1)
print(100*len(new_file[mask])/len(file))

12.65819429904189


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
short = new_file[new_file[:,1]<10]
standart = new_file[(new_file[:,1] >= 10) & (new_file[:,1]<20)]
long_ = new_file[20<=new_file[:,1]]

max = np.min([short.shape[0], standart.shape[0], long_.shape[0]])
np.array([short[:max], standart[:max], long_[:max]])

array([[[ 67660,      5,      6,      0],
        [366174,      7,      9,      0],
        [204134,      5,      3,      1],
        ...,
        [420725,      5,      3,      1],
        [  4747,      1,      9,      0],
        [370915,      5,      4,      1]],

       [[ 94746,     10,      6,      0],
        [ 33941,     18,      9,      0],
        [446597,     15,      5,      1],
        ...,
        [  9831,     15,      7,      0],
        [335859,     12,     14,      0],
        [256812,     10,      3,      1]],

       [[127244,     60,     16,      0],
        [ 23891,     25,      7,      0],
        [157911,     60,     14,      0],
        ...,
        [321217,     65,      7,      0],
        [104584,     48,      8,      0],
        [235518,     23,      8,      0]]], dtype=int32)